"""全局变量区"""
## 经验上一般厚度不超过5
SLICES_THICKNESS = 5
SLICES_THICKNESS_HALF = int(SLICES_THICKNESS / 2)
SLICES_INIT_X_LENGTH = 512
SLICES_INIT_Y_LENGTH = 512
## 中心化裁剪，按此尺寸可最大裁剪且完全保留原有信息
SLICES_X_CROP = 32
SLICES_Y_CROP = 96
SLICES_CROP_X_LENGTH = SLICES_INIT_X_LENGTH - SLICES_X_CROP * 2
SLICES_CROP_Y_LENGTH = SLICES_INIT_Y_LENGTH - SLICES_Y_CROP * 2
## UNET输出的大小，按该尺寸可覆盖最大结节情况
SLICES_X_OUTPUT_LENGTH = 64
SLICES_X_OUTPUT_LENGTH_HALF = int(SLICES_X_OUTPUT_LENGTH / 2)
SLICES_Y_OUTPUT_LENGTH = 64
SLICES_Y_OUTPUT_LENGTH_HALF = int(SLICES_Y_OUTPUT_LENGTH / 2)
